version: '3.1'
name: dbs-nmrweb

services:
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./.docker/app/init.sh:/home/init.sh
      - ./:/var/www/html
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    command: php-fpm

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    entrypoint: /entrypoint.sh
    command: npm run watch

  db:
    image: postgres:9.6.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
