version: '3.1'
name: dbs-nmrweb

services:
  nginx:
    image: nginx:1.20-alpine
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    depends_on:
      - app
      - frontend

  app:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    command: php-fpm

  frontend:
    build:
      context: .
      dockerfile: ./.docker/frontend/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000 # Browsersync
      - 8080:8080 # Webpack dev server
    entrypoint: /entrypoint.sh
    command: npm run dev

  db:
    image: postgres:9.6.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
